DROP TABLE TECHNOLOGY_EXPERIENCE;
DROP TABLE PRODUCT_EXPERIENCE;
DROP TABLE PERSON;
DROP TABLE TECHNOLOGY;
DROP TABLE PRODUCT;

CREATE TABLE PERSON (
id  SERIAL ,
name VARCHAR(100) ,
PRIMARY KEY (id)
);

CREATE TABLE TECHNOLOGY (
id  SERIAL ,
name VARCHAR ,
PRIMARY KEY (id)
);

CREATE TABLE TECHNOLOGY_EXPERIENCE (
person_id  INTEGER ,
technology_id INTEGER ,
year INTEGER ,
rating INTEGER ,
PRIMARY KEY (person_id, technology_id, year)
);

CREATE TABLE PRODUCT_EXPERIENCE (
person_id  INTEGER ,
product_id INTEGER ,
year INTEGER ,
rating INTEGER ,
PRIMARY KEY (person_id, product_id, year)
);

CREATE TABLE PRODUCT (
id  SERIAL ,
name VARCHAR(200) ,
PRIMARY KEY (id)
);

ALTER TABLE TECHNOLOGY_EXPERIENCE ADD FOREIGN KEY (person_id) REFERENCES PERSON (id);
ALTER TABLE TECHNOLOGY_EXPERIENCE ADD FOREIGN KEY (technology_id) REFERENCES TECHNOLOGY (id);
ALTER TABLE PRODUCT_EXPERIENCE ADD FOREIGN KEY (person_id) REFERENCES PERSON (id);
ALTER TABLE PRODUCT_EXPERIENCE ADD FOREIGN KEY (product_id) REFERENCES PRODUCT (id);